In [ ]:
1. Create a NumPy array containing integers from 1 to 10.

In [2]:
import numpy as np
arr = np.arange(1, 11)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
2. Create a 2D NumPy array with shape (3, 4) filled with random float values between 0
and 1.

In [3]:
arr = np.random.rand(3, 4)
print(arr)

[[0.03452909 0.4152857  0.29599774 0.55252673]
 [0.46162331 0.23456597 0.6224665  0.52953915]
 [0.58814818 0.6625491  0.41413019 0.6018202 ]]


In [ ]:
3 Given the following NumPy array:
arr = np.array([10, 20, 30, 40, 50])
Add 5 to each element of the array.

In [4]:
arr = np.array([10, 20, 30, 40, 50])
arr = arr + 5
print(arr)

[15 25 35 45 55]


In [ ]:
4 Given two NumPy arrays:
arr1 = np.array([1, 2, 3, 4]) arr2 = np.array([5, 6, 7, 8])
Concatenate them into a single array.

In [5]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
result = np.concatenate([arr1, arr2])
print(result)

[1 2 3 4 5 6 7 8]


In [ ]:
5. Create a NumPy array of 10 elements with equally spaced values from 0 to 9.

In [6]:
arr = np.linspace(0, 9, 10)
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
Given a NumPy array:
arr = np.array([1, 2, 3, 4, 5, 6])
Reverse the elements in the array.

In [7]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr = arr[::-1]
print(arr)

[6 5 4 3 2 1]


In [ ]:
Create a 3x3 identity matrix using NumPy.

In [8]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
Calculate the mean, median, and standard deviation of the following NumPy array:
arr = np.array([15, 20, 25, 30, 35])


In [9]:
arr = np.array([15, 20, 25, 30, 35])
mean_value = np.mean(arr)
median_value = np.median(arr)
std_deviation = np.std(arr)
print(mean_value,median_value,std_deviation)

25.0 25.0 7.0710678118654755


In [ ]:
9. Given a 2D NumPy array:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Get the diagonal elements of the array.

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
diagonal_elements = np.diagonal(arr)
print(diagonal_elements)

[1 5 9]


In [ ]:
10. Create a NumPy array of 10 random integers between 1 and 100 (inclusive).


In [11]:
arr = np.random.randint(1, 101, 10)
print(arr)

[35  2 57 91 91 59 80 98  4 69]


In [ ]:
11. Create a 2D NumPy array of shape (5, 5) with random integers between 1 and 50
(inclusive).

In [12]:
arr = np.random.randint(1, 51, size=(5, 5))
print(arr)

[[30 25 48 30 37]
 [18  4 20 13  8]
 [38 28 13  1 12]
 [23 30 14 10 15]
 [20 46 19 33 43]]


In [ ]:
12. Given a 2D NumPy array:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Calculate the sum of all the elements in the array.


In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sum_of_elements = np.sum(arr)
print(sum_of_elements)


45


In [ ]:
13. Create a NumPy array with 100 evenly spaced values between 0 and 1 (inclusive) and
reshape it into a 10x10 matrix.


In [15]:
arr = np.linspace(0, 1, 100).reshape(10, 10)
print(arr)


[[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
  0.06060606 0.07070707 0.08080808 0.09090909]
 [0.1010101  0.11111111 0.12121212 0.13131313 0.14141414 0.15151515
  0.16161616 0.17171717 0.18181818 0.19191919]
 [0.2020202  0.21212121 0.22222222 0.23232323 0.24242424 0.25252525
  0.26262626 0.27272727 0.28282828 0.29292929]
 [0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
  0.36363636 0.37373737 0.38383838 0.39393939]
 [0.4040404  0.41414141 0.42424242 0.43434343 0.44444444 0.45454545
  0.46464646 0.47474747 0.48484848 0.49494949]
 [0.50505051 0.51515152 0.52525253 0.53535354 0.54545455 0.55555556
  0.56565657 0.57575758 0.58585859 0.5959596 ]
 [0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
  0.66666667 0.67676768 0.68686869 0.6969697 ]
 [0.70707071 0.71717172 0.72727273 0.73737374 0.74747475 0.75757576
  0.76767677 0.77777778 0.78787879 0.7979798 ]
 [0.80808081 0.81818182 0.82828283 0.83838384 0.84848485 0.85858586
  0.86868687

In [ ]:
14. Given two NumPy arrays:
import numpy as np
arr1 = np.array([1, 2, 3, 4]) arr2 = np.array([5, 6, 7, 8])
Find the common elements between the two arrays.

In [16]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
common_elements = np.intersect1d(arr1, arr2)
print(common_elements)

[]


In [ ]:
15. Create a NumPy array containing 10 random integers between -50 and 50 (inclusive).
Replace all negative values in the array with 0.

In [17]:
arr = np.random.randint(-50, 51, 10)
print(arr)
arr[arr < 0] = 0
print(arr)

[-45  -1   3  30  -2 -41  -8 -35  49   6]
[ 0  0  3 30  0  0  0  0 49  6]


In [ ]:
16. Given a 2D NumPy array:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Calculate the sum of each row and each column separately.

In [18]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sum_of_rows = np.sum(arr, axis=1)
sum_of_columns = np.sum(arr, axis=0)
print(arr)
print(sum_of_rows)
print(sum_of_columns)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 6 15 24]
[12 15 18]


In [ ]:
17. Create a NumPy array of shape (6, 6) with diagonal elements as 1, 2, 3, 4, 5, and 6, and
all other elements as 0.

In [19]:
arr = np.diag(np.arange(1, 7))
print(arr)

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [ ]:
18. Given a NumPy array:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
Normalize the array so that the values range from 0 to 1.

In [20]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
normalized_arr = (arr - arr.min()) / (arr.max() - arr.min())
print(normalized_arr)

[1 2 3 4 5]
[0.   0.25 0.5  0.75 1.  ]


In [ ]:
19. Create a NumPy array with 20 random integers between 1 and 100 (inclusive). Find the
maximum value in the array.



In [21]:
arr = np.random.randint(1, 101, 20)
print(arr)
max_value = np.max(arr)
print(max_value)


[ 7 14 68 85 93 37 79 94 56 22 58 37 13 40 33 13 15 65 53  1]
94


In [ ]:
20. Given two NumPy arrays:
import numpy as np
arr1 = np.array([1, 2, 3, 4]) arr2 = np.array([5, 6, 7, 8])
Compute the element-wise product of the two arrays.

In [22]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
elementwise_product = arr1 * arr2
print(elementwise_product)

[ 5 12 21 32]


In [ ]:
Write a Pandas program to add, subtract, multiple and divide two Pandas Series.
Input: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]
Output:
Add two Series:
0 3
1 7
2 11
3 15
4 19
dtype: int64
Subtract two Series:
0 1
1 1
2 1
3 1
4 1
dtype: int64
Grow Data Skil s
Multiply two Series:
0 2
1 12
2 30
3 56
4 90
dtype: int64
Divide Series1 by Series2:
0 2.000000
1 1.333333
2 1.200000
3 1.142857
4 1.111111
dtype: float64

In [26]:
import pandas as pd

ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])

ds = ds1 + ds2
print("Add two Series:")
print(ds)

ds = ds1 - ds2
print("Subtract two Series:")
print(ds)

ds = ds1 * ds2
print("Multiply two Series:")
print(ds)

ds = ds1 / ds2
print("Divide Series1 by Series2:")
print(ds)


Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


In [ ]:
Q. Create a Pandas DataFrame from the following dictionary, where the keys represent
columns and the values represent the data:
data = { 'Name': ['Alice', 'Bob', 'Charlie', 'David'], 'Age': [25, 30, 22, 28], 'City': ['New York',
'London', 'Paris', 'Tokyo'] }


In [6]:
pip install pandas


Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 22, 28],
    'City': ['New York', 'London', 'Paris', 'Tokyo']
}

df = pd.DataFrame(data)
print(df)




      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   22     Paris
3    David   28     Tokyo


In [ ]:
Q. Given a Pandas DataFrame 'df', select the first 5 rows of the DataFrame.

In [4]:
first_five_rows = df.head(5)
print(df)


      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   22     Paris
3    David   28     Tokyo


In [ ]:
Q. Create a new column 'Salary' in the DataFrame 'df' with random integer values
between 50000 and 80000 (inclusive).

In [7]:
import pandas as pd
import numpy as np

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 22, 28],
    'City': ['New York', 'London', 'Paris', 'Tokyo']
}

df = pd.DataFrame(data)

# Generate random salary values between 50000 and 80000
salary_values = np.random.randint(50000, 80001, size=len(df))

# Add the 'Salary' column to the DataFrame
df['Salary'] = salary_values

print(df)


      Name  Age      City  Salary
0    Alice   25  New York   69944
1      Bob   30    London   70522
2  Charlie   22     Paris   56295
3    David   28     Tokyo   61591


In [ ]:
Q. Given two Pandas DataFrames 'df1' and 'df2' with the same columns, concatenate
them vertically.

In [11]:
import pandas as pd

# Define the first DataFrame (df1)
data1 = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 22]
}
df1 = pd.DataFrame(data1)

# Define the second DataFrame (df2)
data2 = {
    'Name': ['David', 'Eva', 'Frank'],
    'Age': [28, 24, 29]
}
df2 = pd.DataFrame(data2)

# Concatenate the DataFrames vertically
concatenated_df = pd.concat([df1, df2])

# Print the concatenated DataFrame
print(concatenated_df)



      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   22
0    David   28
1      Eva   24
2    Frank   29


pd.concat() function is used to concatenate them vertically. import pandas as pd

# AssuminWeou have df1 and df2 defined already
# df1 = ...
# df2 = ...

concatenated_df = pd.concat([df1, df2])
print(concatenated_df)

In [ ]:
Q. Create a new DataFrame named 'df_filtered' from 'df', containing only rows where the
'Age' column is greater than 25.

In [12]:
import pandas as pd

# Assuming you have defined the DataFrame 'df' already
# df = ...

df_filtered = df[df['Age'] > 25]
print(df_filtered)


    Name  Age    City  Salary
1    Bob   30  London   70522
3  David   28   Tokyo   61591


In [ ]:
Q. Given a Pandas DataFrame 'df', sort the DataFrame based on the 'Age' column in
ascending order.

In [13]:
sorted_df = df.sort_values(by='Age', ascending=True)
print(sorted_df)


      Name  Age      City  Salary
2  Charlie   22     Paris   56295
0    Alice   25  New York   69944
3    David   28     Tokyo   61591
1      Bob   30    London   70522


In [ ]:
Q. Calculate the mean and median of the 'Salary' column in the DataFrame 'df'.

In [14]:
mean_salary = df['Salary'].mean()
median_salary = df['Salary'].median()
print(mean_salary, median_salary)

64588.0 65767.5


In [5]:
import pandas as pd

# Use a raw string literal
df = pd.read_csv(r"C:\Users\saura\Downloads\Pyhtonclass4\NBADATASET\nba.csv")
print(df)



              Name            Team  Number Position  Age  Weight  \
0    Avery Bradley  Boston Celtics       0       PG   25     180   
1      Jae Crowder  Boston Celtics      99       SF   25     235   
2     John Holland  Boston Celtics      30       SG   27     205   
3      R.J. Hunter  Boston Celtics      28       SG   22     185   
4    Jonas Jerebko  Boston Celtics       8       PF   29     231   
..             ...             ...     ...      ...  ...     ...   
452     Trey Lyles       Utah Jazz      41       PF   20     234   
453   Shelvin Mack       Utah Jazz       8       PG   26     203   
454      Raul Neto       Utah Jazz      25       PG   24     179   
455   Tibor Pleiss       Utah Jazz      21        C   26     256   
456    Jeff Withey       Utah Jazz      24        C   26     231   

               College     Salary  
0                Texas  7730337.0  
1            Marquette  6796117.0  
2    Boston University        NaN  
3        Georgia State  1148640.0  
4  

In [3]:
Q. Read the csv provide(nba.csv) into a DataframeDisplay:
*Number of rows and columns in dataframe
* Top 10 and bottom 10 rows
* Summary statistics for numerical columns
*Datatype of columns in dataframe
* Length of the data
* Print all the Rows from index 100 to 200

In [6]:
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv(r"C:\Users\saura\Downloads\Pyhtonclass4\NBADATASET\nba.csv")

# Number of rows and columns in the dataframe
print("Number of rows and columns:", df.shape)

# Top 10 rows
print("Top 10 rows:")
print(df.head(10))

# Bottom 10 rows
print("Bottom 10 rows:")
print(df.tail(10))

# Summary statistics for numerical columns
print("Summary statistics for numerical columns:")
print(df.describe())

# Datatype of columns in the dataframe
print("Datatype of columns:")
print(df.dtypes)

# Length of the data
print("Length of the data:", len(df))

# Print all the rows from index 100 to 200
print("Rows from index 100 to 200:")
print(df.iloc[100:201])


Number of rows and columns: (457, 8)
Top 10 rows:
            Name            Team  Number Position  Age  Weight  \
0  Avery Bradley  Boston Celtics       0       PG   25     180   
1    Jae Crowder  Boston Celtics      99       SF   25     235   
2   John Holland  Boston Celtics      30       SG   27     205   
3    R.J. Hunter  Boston Celtics      28       SG   22     185   
4  Jonas Jerebko  Boston Celtics       8       PF   29     231   
5   Amir Johnson  Boston Celtics      90       PF   29     240   
6  Jordan Mickey  Boston Celtics      55       PF   21     235   
7   Kelly Olynyk  Boston Celtics      41        C   25     238   
8   Terry Rozier  Boston Celtics      12       PG   22     190   
9   Marcus Smart  Boston Celtics      36       PG   22     220   

             College      Salary  
0              Texas   7730337.0  
1          Marquette   6796117.0  
2  Boston University         NaN  
3      Georgia State   1148640.0  
4                NaN   5000000.0  
5            